export type Tier = "platinum" | "gold" | "silver" | "bronze";

export type Teacher = {
  id: string;
  name: string;
  role: string;
  img: string;
  subjects: string[];
  rating: string;
  students: string;
  bio: string;
  badge: string;
  experienceYears: number;
  city: string;
  phone?: string;
  online: boolean;
  offline: boolean;
  stages: string[];
  gender: "male" | "female";
  // Computed
  murtaqaScore: number;
  tier: Tier;
};

// ──────────────────────────────────────────────────────────
// 🎯 MOTQEN SCORE FORMULA (out of 100)
//
//  • تقييم الأهالي      → 30 pts   (rating / 5) × 30
//  • سنوات الخبرة        → 25 pts   min(years / 30, 1) × 25
//  • تنوع المواد         → 15 pts   min(subjects.len / 5, 1) × 15
//  • تنوع المراحل        → 10 pts   min(stages.len / 4, 1) × 10
//  • التوفر (أون+أوف)    → 20 pts   online×10 + offline×10
//
//  TIERS:
//    🏆 بلاتيني   ≥ 90
//    ⭐ ذهبي      80–89
//    🥈 فضي       70–79
//    🥉 برونزي    < 70
// ──────────────────────────────────────────────────────────

function calcScore(t: Omit<Teacher, "murtaqaScore" | "tier">): number {
  const ratingScore = (parseFloat(t.rating) / 5) * 30;
  const expScore = Math.min(t.experienceYears / 30, 1) * 25;
  const subjectScore = Math.min(t.subjects.length / 5, 1) * 15;
  const stageScore = Math.min(t.stages.length / 4, 1) * 10;
  const availScore = (t.online ? 10 : 0) + (t.offline ? 10 : 0);
  return Math.round(
    ratingScore + expScore + subjectScore + stageScore + availScore,
  );
}

function getTier(score: number): Tier {
  if (score >= 90) return "platinum";
  if (score >= 80) return "gold";
  if (score >= 70) return "silver";
  return "bronze";
}

function make(t: Omit<Teacher, "murtaqaScore" | "tier">): Teacher {
  const score = calcScore(t);
  return { ...t, murtaqaScore: score, tier: getTier(score) };
}

// ──────────────────────────────────────────────────────────
export const TIER_META: Record<
  Tier,
  {
    label: string;
    emoji: string;
    color: string;
    bg: string;
    border: string;
    glow: string;
  }
> = {
  platinum: {
    label: "بلاتيني",
    emoji: "🏆",
    color: "text-cyan-300",
    bg: "bg-cyan-400/10",
    border: "border-cyan-400/30",
    glow: "shadow-cyan-400/20",
  },
  gold: {
    label: "ذهبي",
    emoji: "⭐",
    color: "text-yellow-400",
    bg: "bg-yellow-400/10",
    border: "border-yellow-400/30",
    glow: "shadow-yellow-400/15",
  },
  silver: {
    label: "فضي",
    emoji: "🥈",
    color: "text-slate-300",
    bg: "bg-slate-400/10",
    border: "border-slate-400/25",
    glow: "shadow-slate-400/10",
  },
  bronze: {
    label: "برونزي",
    emoji: "🥉",
    color: "text-orange-400",
    bg: "bg-orange-400/8",
    border: "border-orange-400/20",
    glow: "shadow-orange-400/10",
  },
};

export const SCORE_CRITERIA = [
  {
    label: "تقييم الأهالي",
    max: 30,
    icon: "⭐",
    desc: "بناءً على تقييمات أولياء الأمور من 5 نجوم",
  },
  {
    label: "سنوات الخبرة",
    max: 25,
    icon: "💼",
    desc: "أقصى نقاط لـ 30 سنة فأكثر",
  },
  {
    label: "تنوع المواد",
    max: 15,
    icon: "📚",
    desc: "كلما زادت المواد زادت النقاط (أقصى 5 مواد)",
  },
  {
    label: "تنوع المراحل",
    max: 10,
    icon: "🎓",
    desc: "من ابتدائي حتى جامعي (أقصى 4 مراحل)",
  },
  {
    label: "التوفر",
    max: 20,
    icon: "💻",
    desc: "10 نقاط للأونلاين + 10 نقاط للأوفلاين",
  },
];

// ──────────────────────────────────────────────────────────
export const teachers: Teacher[] = [
  make({
    id: "mohammed-abu-alhadid",
    name: "محمد أبو الحديد",
    role: "مدرس لغة عربية + قدرات لفظي",
    img: "/assets/imgs/mohammed-abu-alhadid.jpeg",
    subjects: ["لغة عربية", "قدرات لفظي", "بلاغة"],
    rating: "5.0",
    students: "65+",
    bio: "خبرة 35 سنة في تدريس اللغة العربية لجميع المراحل مع تخصص في القدرات اللفظي والبلاغة.",
    badge: "خبير 35 سنة",
    experienceYears: 35,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "ahmed-antar",
    name: "أحمد عنتر (أبو محمد)",
    role: "مدرس لغة إنجليزية — تأسيس وجميع المراحل",
    img: "/assets/imgs/ahmed-antar.jpeg",
    subjects: ["لغة إنجليزية", "تأسيس"],
    rating: "5.0",
    students: "70+",
    bio: "خبرة 32 سنة في تأسيس وتعليم اللغة الإنجليزية من الصفر حتى المستويات المتقدمة والجامعية.",
    badge: "خبير 32 سنة",
    experienceYears: 32,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي", "جامعي"],
    gender: "male",
  }),
  make({
    id: "hisham-mohammed",
    name: "هشام محمد",
    role: "مدرس رياضيات — جميع المراحل + قدرات",
    img: "/assets/imgs/hisham-mohammed.jpeg",
    subjects: ["رياضيات", "قدرات كمي"],
    rating: "5.0",
    students: "60+",
    bio: "خبرة 30 سنة في تدريس الرياضيات مع تبسيط المفاهيم وإعداد الطلاب لاختبارات القدرات.",
    badge: "خبير 30 سنة",
    experienceYears: 30,
    city: "تبوك",
    online: true,
    offline: false,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "mohammed-shaarawi",
    name: "محمد الشعراوي",
    role: "معلم قرآن + عربي + إنجليزي",
    img: "/assets/imgs/mohammed-shaarawi.jpeg",
    subjects: ["قرآن كريم", "لغة عربية", "لغة إنجليزية"],
    rating: "5.0",
    students: "80+",
    bio: "خبرة أكثر من 30 سنة في المملكة في تدريس القرآن والمناهج الدراسية وتأسيس الطلاب.",
    badge: "خبير المملكة",
    experienceYears: 30,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط"],
    gender: "male",
  }),
  make({
    id: "ismaeel-abdelmoghni",
    name: "إسماعيل عبد المغني",
    role: "مدرس لغة إنجليزية — جميع المناهج",
    img: "/assets/imgs/ismaeel-abdelmoghni.jpeg",
    subjects: ["لغة إنجليزية"],
    rating: "5.0",
    students: "55+",
    bio: "خبرة 28 سنة في تدريس المناهج الحكومية والأهلية والدولية (أمريكي / بريطاني).",
    badge: "International",
    experienceYears: 28,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "ibrahim-eid",
    name: "إبراهيم عيد",
    role: "مدرس لغة إنجليزية — جميع المراحل",
    img: "/assets/imgs/ibrahim-eid.jpeg",
    subjects: ["لغة إنجليزية"],
    rating: "5.0",
    students: "50+",
    bio: "خبرة 27 سنة في تدريس اللغة الإنجليزية لجميع المراحل مع أسلوب مبسط يركز على الفهم والتطبيق العملي.",
    badge: "خبير 25+ سنة",
    experienceYears: 27,
    city: "تبوك",
    online: true,
    offline: false,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "ahmed-ata",
    name: "أحمد عطا صابر",
    role: "معلم خبير لغة إنجليزية + تأسيس شامل",
    img: "/assets/imgs/ahmed-ata-saber.jpg",
    subjects: ["إنجليزي", "رياضيات", "علوم", "تأسيس"],
    rating: "5.0",
    students: "25+ سنة خبرة",
    bio: "يتميز بقدرته على تأسيس الطلاب من الصفر وحتى الاحتراف، مع تبسيط المناهج بطريقة تناسب الجميع.",
    badge: "خبير تأسيس",
    experienceYears: 25,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "dr-badr",
    name: "الأستاذ بدر فايد",
    role: "مدرس اللغة الإنجليزية | مناهج متقدمة",
    img: "/assets/imgs/dr.badr.jpg",
    subjects: ["إنجليزي", "تأسيس لغة", "جامعي"],
    rating: "5.0",
    students: "22+ سنة خبرة",
    bio: "يمتلك خبرة طويلة في تدريس اللغة الإنجليزية وفق أحدث المناهج، ويركّز على بناء أساس قوي للطالب.",
    badge: "خبير إنجليزي",
    experienceYears: 22,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["متوسط", "ثانوي", "جامعي"],
    gender: "male",
  }),
  make({
    id: "sayed-qaoud",
    name: "سيد قاعود",
    role: "معلم تأسيس وتحفيظ قرآن",
    img: "/assets/imgs/sayed-qaoud.jpeg",
    subjects: ["تأسيس", "قرآن كريم"],
    rating: "5.0",
    students: "40+",
    bio: "خبرة 20 سنة في تأسيس الطلاب وتحفيظ القرآن بأسلوب تربوي مبسط ومؤثر.",
    badge: "محفظ قرآن",
    experienceYears: 20,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي"],
    gender: "male",
  }),
  make({
    id: "mohammed-ali",
    name: "محمد علي محجوب",
    role: "معلم خبير لغة إنجليزية",
    img: "/assets/imgs/mohammed-ali-mahjoub.jpeg",
    subjects: ["إنجليزي", "مناهج دولية", "جامعي"],
    rating: "5.0",
    students: "20+ سنة خبرة",
    bio: "يتميز بخبرة طويلة في تعليم اللغة إنجليزية لمختلف الأعمار، ويعتمد على أساليب تفاعلية حديثة.",
    badge: "خبير إنجليزي",
    experienceYears: 20,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["متوسط", "ثانوي", "جامعي"],
    gender: "male",
  }),
  make({
    id: "nader-saber",
    name: "نادر صابر",
    role: "مدرس ابتدائي شامل",
    img: "/assets/imgs/nader-saber.jpeg",
    subjects: ["لغتي", "لغة إنجليزية", "رياضيات"],
    rating: "5.0",
    students: "45+",
    bio: "خبرة أكثر من 20 سنة في تأسيس طلاب المرحلة الابتدائية في جميع المواد الأساسية.",
    badge: "خبير ابتدائي",
    experienceYears: 20,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي"],
    gender: "male",
  }),
  make({
    id: "abdelnaser",
    name: "عبدالناصر محمد إبراهيم",
    role: "خبير منهج سعودي — 14 عاماً",
    img: "/assets/imgs/abdelnaser.jpg",
    subjects: ["قدرات", "تحصيلي", "ثانوي"],
    rating: "4.9",
    students: "14 سنة خبرة",
    bio: "يساعد الطلاب على تحقيق نتائج متميزة في القدرات والتحصيلي باستراتيجيات ذكية مجربة على مدى 14 عاماً.",
    badge: "خبير قدرات",
    experienceYears: 14,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ثانوي", "جامعي"],
    gender: "male",
  }),
  make({
    id: "yaser-saber",
    name: "ياسر صابر",
    role: "معلم متميز",
    img: "/assets/imgs/yaser-saber.jpeg",
    subjects: ["تأسيس", "متابعة", "رياضيات"],
    rating: "4.8",
    students: "خبرة واسعة",
    bio: "مدرس خبير يركز على تحسين مستوى الطلاب وتطوير مهاراتهم الدراسية بشكل ملحوظ.",
    badge: "معلم متميز",
    experienceYears: 12,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط"],
    gender: "male",
  }),
  make({
    id: "ahmed-hashem",
    name: "أحمد هاشم سباق",
    role: "مدرس أساسي — ابتدائي",
    img: "/assets/imgs/ahmed-hashem.jpg",
    subjects: ["لغتي", "رياضيات", "تأسيس"],
    rating: "5.0",
    students: "20+",
    bio: "يركّز على تعليم الأطفال بطريقة تفاعلية تضمن الفهم العميق، مما يبني أساساً قويًا في القراءة والكتابة والحساب.",
    badge: "مدرس تأسيس",
    experienceYears: 10,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي"],
    gender: "male",
  }),
  make({
    id: "ramadan-al-hawari",
    name: "رمضان الهواري",
    role: "مدرس لغة إنجليزية + ترجمة",
    img: "/assets/imgs/ramadan-al-hawari.jpeg",
    subjects: ["لغة إنجليزية"],
    rating: "5.0",
    students: "30+",
    bio: "خبرة في التعليم الأكاديمي والترجمة مع أسلوب تفاعلي يضمن أعلى استفادة للطالب.",
    badge: "تفاعلي",
    experienceYears: 10,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "abdelmonem-hossam",
    name: "عبدالمنعم حسام",
    role: "مدرس إنجليزي + رياضيات",
    img: "/assets/imgs/abdelmonem-hossam.jpeg",
    subjects: ["لغة إنجليزية", "رياضيات"],
    rating: "5.0",
    students: "25+",
    bio: "خبرة 9 سنوات في تبسيط المواد العلمية واللغوية وتحسين مستوى الطلاب.",
    badge: "متعدد المهارات",
    experienceYears: 9,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط"],
    gender: "male",
  }),
  make({
    id: "mohammed-abdelhakim",
    name: "محمد عبد الحكيم",
    role: "مدرس أحياء + تأسيس",
    img: "/assets/imgs/mohammed-abdelhakim.jpeg",
    subjects: ["أحياء", "تأسيس"],
    rating: "5.0",
    students: "25+",
    bio: "خبرة 6 سنوات في المملكة، يركز على تبسيط الأحياء وبناء أساس قوي للطلاب.",
    badge: "مدرس نشط",
    experienceYears: 6,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "osama-ali",
    name: "أسامة علي عبدالجواد",
    role: "علوم وأحياء وقرآن كريم",
    img: "/assets/imgs/osama ali.jpg",
    subjects: ["علوم", "أحياء", "قرآن", "تجويد"],
    rating: "4.8",
    students: "5+ سنوات",
    bio: "يجمع بين العلوم الأكاديمية والتربوية، مع خبرة في تحفيظ القرآن والتجويد بأسلوب شيّق.",
    badge: "محفظ قرآن",
    experienceYears: 5,
    city: "تبوك",
    online: true,
    offline: false,
    stages: ["ابتدائي", "متوسط"],
    gender: "male",
  }),
  make({
    id: "mohammed-ahmed-saad",
    name: "محمد أحمد سعد",
    role: "متخصص قدرات + تحصيلي + علوم",
    img: "/assets/imgs/mohammed-ahmed-saad.jpg",
    subjects: ["قدرات", "تحصيلي", "علوم"],
    rating: "4.9",
    students: "5 سنوات خبرة",
    bio: "يساعد الطلاب على تحسين نتائجهم من خلال التدريب المكثف على نماذج الاختبارات الحديثة.",
    badge: "خبير قدرات",
    experienceYears: 5,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ثانوي", "جامعي"],
    gender: "male",
  }),
  make({
    id: "hashem-sewak",
    name: "هاشم السواق",
    role: "متخصص في مادة الكيمياء",
    img: "/assets/imgs/hashem-al-sawaq.jpg",
    subjects: ["كيمياء", "علوم"],
    rating: "4.8",
    students: "3 سنوات خبرة",
    bio: "يقدّم شرحًا مبسطًا لمادة الكيمياء يساعد الطلاب على فهم الأساسيات بسهولة وتحقيق نتائج أفضل.",
    badge: "مدرس كيمياء",
    experienceYears: 3,
    city: "تبوك",
    online: false,
    offline: true,
    stages: ["ثانوي"],
    gender: "male",
  }),
  make({
    id: "mahmoud-muslim",
    name: "محمود مسلم",
    role: "معلم أحياء للمرحلة الثانوية",
    img: "/assets/imgs/mahmoud-muslim.jpeg",
    subjects: ["أحياء", "تحصيلي", "علوم"],
    rating: "4.9",
    students: "3 سنوات خبرة",
    bio: "حاصل على الرخصة المهنية التعليمية تخصص الأحياء، يتميز بمستوى ممتاز في المادة العلمية.",
    badge: "خبير أحياء",
    experienceYears: 3,
    city: "تبوك",
    online: true,
    offline: false,
    stages: ["ثانوي"],
    gender: "male",
  }),
  make({
    id: "fatouh-qutb",
    name: "فتوح قطب البسيوني",
    role: "معلم خبير",
    img: "/assets/imgs/fatouh-qutb.jpg",
    subjects: ["لغة عربية", "تأسيس"],
    rating: "5.0",
    students: "خبرة طويلة",
    bio: "معلم قدير يمتلك سنوات طويلة من الخبرة في التعليم وبناء مهارات الطلاب الأساسية.",
    badge: "خبير تعليمي",
    experienceYears: 30,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "mustafa-abdelrazek",
    name: "مصطفي عبد الرازق محمد فرج",
    role: "مدرس كيمياء وعلوم — جامعي وثانوي",
    img: "/assets/imgs/mustafa-abdelrazek.jpeg",
    subjects: ["كيمياء", "علوم", "chemistry", "science", "كيمياء جامعية"],
    rating: "5.0",
    students: "15+ سنة خبرة",
    bio: "خبير في تدريس المناهج المصرية والسعودية لمناهج العلوم والكيمياء لجميع المراحل، بالإضافة إلى تدريس الكيمياء لطلاب الجامعات والكليات العلمية (طب، صيدلة، علوم). خبرة في تدريس طلاب جامعة الملك فيصل بالأحساء.",
    badge: "خبير جامعي",
    experienceYears: 15,
    city: "الأحساء",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي", "جامعي"],
    gender: "male",
  }),
  make({
    id: "ahmed-marouf",
    name: "أحمد معروف",
    role: "مدرس لغة عربية + قرآن + قدرات لفظي",
    img: "/assets/imgs/ahmed-marouf.jpeg",
    subjects: ["لغة عربية", "قرآن كريم", "قدرات لفظي"],
    rating: "5.0",
    students: "45+",
    bio: "خبير لغة عربية وقدرات معتمد.",
    badge: "لغة عربية",
    experienceYears: 20,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "hany-elawady",
    name: "هاني عبد الوهاب العوضي",
    role: "مدرس جامعة + كيمياء + فيزياء + تحصيلي",
    img: "/assets/imgs/hany-elawady.jpeg",
    subjects: ["كيمياء", "فيزياء", "تحصيلي"],
    rating: "5.0",
    students: "90+",
    bio: "خبير جامعي متخصص في المواد العلمية والتحصيلي.",
    badge: "خبير جامعي",
    experienceYears: 33,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "reda-amar",
    name: "رضا محمد الصابر عمار",
    role: "مدرس كيمياء — جميع المراحل",
    img: "/assets/imgs/reda-amar.jpeg",
    subjects: ["كيمياء"],
    rating: "5.0",
    students: "50+",
    bio: "حاصل على بكالوريوس في العلوم والتربية تخصص فيزياء وكيمياء، يتبع أسلوبًا مبسطًا في الشرح ويتعامل مع جميع المستويات مع متابعة مستمرة لولي الأمر.",
    badge: "كيمياء",
    experienceYears: 18,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "mohammed-abdelalim-data",
    name: "محمد عبدالعليم",
    role: "مدرس رياضيات + قدرات + تحصيلي",
    img: "/assets/imgs/mohammed-abdelalim.jpeg",
    subjects: ["رياضيات", "قدرات", "تحصيلي"],
    rating: "5.0",
    students: "60+",
    bio: "خبير رياضيات متميز.",
    badge: "رياضيات",
    experienceYears: 17,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "ahmed-el-sayed",
    name: "أحمد السيد محمد",
    role: "مدرس تأسيس + قرآن — ابتدائي",
    img: "/assets/imgs/ahmed-elsayed.jpeg",
    subjects: ["تأسيس", "قرآن كريم"],
    rating: "5.0",
    students: "40+",
    bio: "مدرس تأسيس بطريقة نور البيان بشكل تدريجي وسهل، ومحفظ قرآن معتمد بجمعية تحفيظ القرآن الكريم بتبوك.",
    badge: "تأسيس وقرآن",
    experienceYears: 10,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي"],
    gender: "male",
  }),
  make({
    id: "abdelaziz-ali",
    name: "عبدالعزيز علي",
    role: "مدرس دوائر كهربائية وآلات — كليات التقنية",
    img: "/assets/imgs/abdelaziz-ali.jpeg",
    subjects: ["دوائر كهربائية 1", "دوائر كهربائية 2", "آلات تيار مستمر"],
    rating: "5.0",
    students: "30+",
    bio: "متخصص في هندسة الكهرباء.",
    badge: "هندسة كهربائية",
    experienceYears: 10,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["جامعة"],
    gender: "male",
  }),
  make({
    id: "mohammed-abdessalam",
    name: "محمد عبدالسلام",
    role: "مدرس لغة إنجليزية + ترجمة",
    img: "/assets/imgs/mohammed-abdessalam.jpeg",
    subjects: ["لغة إنجليزية"],
    rating: "5.0",
    students: "45+",
    bio: "خريج لغات وترجمة، خبرة في التدريس والتأسيس لجميع المراحل والجامعات، وخبرة في الترجمة التحريرية والفورية.",
    badge: "إنجليزي وترجمة",
    experienceYears: 8,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "mohammed-abdelhamid",
    name: "محمد عبد الحميد",
    role: "مدرس لغة إنجليزية — جميع المراحل",
    img: "/assets/imgs/mohammed-abdelhamid.jpeg",
    subjects: ["لغة إنجليزية"],
    rating: "5.0",
    students: "70+",
    bio: "خبرة طويلة في المكاتب التعليمية.",
    badge: "إنجليزي",
    experienceYears: 30,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "ryad-salam",
    name: "رياض عبدالعظيم سلام",
    role: "مدرس فيزياء + كيمياء + تحصيلي",
    img: "/assets/imgs/ryad-salam.jpeg",
    subjects: ["فيزياء", "كيمياء", "تحصيلي"],
    rating: "5.0",
    students: "25+",
    bio: "خبير في المواد العلمية.",
    badge: "فيزياء وكيمياء",
    experienceYears: 15,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "abdellatif-shaker",
    name: "عبداللطيف شاكر عبداللطيف",
    role: "مدرس شريعة إسلامية + قانون — جامعة",
    img: "/assets/imgs/abdellatif-shaker.jpeg",
    subjects: ["شريعة", "قانون"],
    rating: "5.0",
    students: "40+",
    bio: "متخصص في الدراسات القانونية والشريعة.",
    badge: "شريعة وقانون",
    experienceYears: 25,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["جامعة"],
    gender: "male",
  }),
  make({
    id: "mohammed-moussa",
    name: "محمد عبد الله موسى سليمان",
    role: "مدرس فيزياء — جميع المراحل",
    img: "/assets/imgs/mohammed-moussa.jpeg",
    subjects: ["فيزياء"],
    rating: "5.0",
    students: "100+",
    bio: "خبير فيزياء متميز.",
    badge: "فيزياء",
    experienceYears: 35,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["متوسط", "ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "ahmed-gad",
    name: "أحمد جاد",
    role: "مدرس خبير — جميع المراحل",
    img: "/assets/imgs/ahmed-gad.jpeg",
    subjects: ["لغة عربية", "تأسيس", "متابعة"],
    rating: "5.0",
    students: "جديد",
    bio: "خبرة واسعة في التدريس والتعامل مع مختلف المستويات الدراسية بأساليب حديثة ومبتكرة.",
    badge: "انضم حديثاً",
    experienceYears: 15,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "khaled-mostafa-ramadan",
    name: "خالد مصطفى رمضان محمد",
    role: "مدرس إدارة الرياضات المائية",
    img: "/assets/imgs/khaled-mostafa-ramadan.jpeg",
    subjects: ["إدارة رياضية", "رياضات مائية"],
    rating: "5.0",
    students: "20+",
    bio: " مدرس ادارة الرياضات المائية بقسم الادارة الرياضية والترويح كلية علوم الرياضة جامعة أسيوط",
    badge: "جامعي",
    experienceYears: 12,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["جامعة"],
    gender: "male",
  }),
  make({
    id: "mohamed-noman",
    name: "محمد نعمان",
    role: "مدرس لغة إنجليزية — جميع المراحل",
    img: "/assets/imgs/mohamed-noman.jpeg",
    subjects: ["لغة إنجليزية"],
    rating: "5.0",
    students: "50+",
    bio: "تأسيس اللغة الإنجليزية لجميع المراحل من KG حتى الجامعة، مع خبرة في المناهج الحكومية والإنترناشونال.",
    badge: "خبير إنجليزي",
    experienceYears: 12,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["KG", "ابتدائي", "متوسط", "ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "mohamed-ahmed-safwat",
    name: "محمد أحمد صفوت محمد عمر",
    role: "مدرس كيمياء — ثانوي",
    img: "/assets/imgs/mohamed-ahmed-safwat.jpeg",
    subjects: ["كيمياء"],
    rating: "5.0",
    students: "65+",
    bio: "خبير كيمياء متميز.",
    badge: "كيمياء",
    experienceYears: 23,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ثانوي"],
    gender: "male",
  }),
  make({
    id: "tarek-abdelwahab-abdelaziz",
    name: "طارق عبدالوهاب عبدالعزيز",
    role: "مدرس لغة إنجليزية + ترجمة",
    img: "/assets/imgs/tarek-abdelwahab-abdelaziz.jpeg",
    subjects: ["لغة إنجليزية"],
    rating: "5.0",
    students: "100+",
    bio: "مدرس لغة إنجليزية وآدابها ومترجم حر، متخصص في اختبار STEP، خبرة طويلة في التدريس والترجمة لأكثر من 35 عامًا.",
    badge: "خبير 35 سنة",
    experienceYears: 38,
    city: "تبوك",
    online: false,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "ahmed-abdelkarim-al-zubaidi",
    name: "أحمد عبدالكريم الزبيدي",
    role: "مدرس أحياء + كيمياء + تحصيلي",
    img: "/assets/imgs/ahmed-abdelkarim-al-zubaidi.jpeg",
    subjects: ["أحياء", "كيمياء", "تحصيلي"],
    rating: "5.0",
    students: "45+",
    bio: "تدريس الأحياء والكيمياء للمرحلة الثانوية بالإضافة إلى التحصيلي، مع تدريس مواد الجامعة (Biology & Chemistry).",
    badge: "أحياء وكيمياء",
    experienceYears: 9,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ثانوي", "جامعة"],
    gender: "male",
  }),
  // --- New Teachers from User Request ---
  make({
    id: "fathy-ahmed-mahmoud",
    name: "فتحي أحمد محمود",
    role: "معلم لغة عربية متميز",
    img: "/assets/imgs/fathy-ahmed-mahmoud.jpeg",
    subjects: ["اللغة العربية"],
    rating: "5.0",
    students: "95+",
    bio: "خبرة 30 عاماً في تدريس اللغة العربية في تبوك. أسلوب تعليمي متميز يجمع بين الأونلاين والحضوري.",
    badge: "خبير 30 عاماً",
    experienceYears: 30,
    city: "تبوك",
    phone: "0565305040",
    online: true,
    offline: true,
    stages: ["ابتدائي"],
    gender: "male",
  }),
  make({
    id: "asmaa-metwally-awadh",
    name: "أسماء متولي عوض",
    role: "معلمة لغة عربية وتأسيس",
    img: "/assets/imgs/asmaa-metwally-awadh.jpeg",
    subjects: ["لغة عربية", "تأسيس"],
    rating: "5.0",
    students: "30+",
    bio: "خبرة 6 سنوات في تدريس اللغة العربية وتأسيس الطلاب للمرحلتين الابتدائية والمتوسطة في تبوك.",
    badge: "تأسيس متميزة",
    experienceYears: 6,
    city: "تبوك",
    phone: "0511393693",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط"],
    gender: "female",
  }),
  make({
    id: "hazem-youssef-darwish",
    name: "حازم يوسف درويش",
    role: "معلم أحياء وتحصيلي متميز",
    img: "/assets/imgs/hazem-youssef-darwish.jpeg",
    subjects: ["الأحياء", "تحصيلي"],
    rating: "5.0",
    students: "50+",
    bio: "معلم أحياء تحصيلي وعام متميز، خبرة في تدريس المناهج السعودية والدولية لأكثر من 8 سنوات.",
    badge: "خبير أحياء",
    experienceYears: 8,
    city: "تبوك",
    phone: "0549807498",
    online: true,
    offline: true,
    stages: ["ثانوي"],
    gender: "male",
  }),
  make({
    id: "mohammed-fadel-elbakr",
    name: "محمد فاضل السيد بكر",
    role: "معلم تحصيلي وقرآن كريم",
    img: "/assets/imgs/mohammed-fadel-elbakr.jpeg",
    subjects: ["لغة عربية", "قرآن كريم", "تحصيلي"],
    rating: "5.0",
    students: "85+",
    bio: "معلم بمدارس العصر الثانوية، خبرة 20 عاماً. مدرب دورات نور البيان وتعليم القراءة بالقرآن الكريم.",
    badge: "خبير 20 عاماً",
    experienceYears: 20,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "educational-consultant",
    name: "المستشار التربوي (مصطفى كمال بدوي)",
    role: "خبير تربية خاصة وتأسيس",
    img: "/assets/imgs/educational-consultant.jpeg",
    subjects: ["تأسيس", "صعوبات تعلم", "تربية خاصة", "تخاطب", "محو أمية", "حساب ذهني"],
    rating: "5.0",
    students: "120+",
    bio: "ماجستير تربية خاصة، خبرة 26 سنة. معلم تأسيس لطلاب صعوبات التعلم والتربية الخاصة، أخصائي تخاطب ومدرب حساب ذهني UCMAS.",
    badge: "خبير 26 سنة",
    experienceYears: 26,
    city: "تبوك",
    phone: "0559501829",
    online: true,
    offline: true,
    stages: ["ابتدائي"],
    gender: "male",
  }),
  make({
    id: "sara-khaled",
    name: "سارة خالد",
    role: "معلمة لغة عربية وتأسيس",
    img: "/assets/imgs/sara-khaled.jpeg",
    subjects: ["لغة عربية", "تأسيس"],
    rating: "5.0",
    students: "55+",
    bio: "خبرة 15 عاماً في تدريس اللغة العربية أونلاين لجميع المراحل الابتدائية والتأسيس.",
    badge: "خبير 15 سنة",
    experienceYears: 15,
    city: "تبوك",
    online: true,
    offline: false,
    stages: ["ابتدائي"],
    gender: "female",
  }),
  make({
    id: "ashraf-ragab-abdelrahim",
    name: "اشرف رجب عبدالرحيم",
    role: "مشرف لغة إنجليزية",
    img: "/assets/imgs/ashraf-ragab-abdelrahim.jpeg",
    subjects: ["لغة إنجليزية"],
    rating: "5.0",
    students: "110+",
    bio: "خريج ألسن انجليزي دفعة 91. خبرة 23 سنة بمدارس عثمان بن عفان الأهلية، مشرف لغة إنجليزية حالياً.",
    badge: "مشرف تربوي",
    experienceYears: 23,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "ehab-abdelhady",
    name: "إيهاب عبد الهادي",
    role: "معلم لغة عربية ورياضيات",
    img: "/assets/imgs/ehab-abdelhady.jpeg",
    subjects: ["لغة عربية", "رياضيات", "قدرات", "مواد علمية"],
    rating: "5.0",
    students: "80+",
    bio: "خبرة 21 عاماً في تدريس اللغة العربية لجميع المراحل حتى الجامعة والقدرات، وخبير في الرياضيات للمناهج السعودية.",
    badge: "خبير 21 عاماً",
    experienceYears: 21,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "wael-ahmed-hamza",
    name: "وائل احمد حمزة",
    role: "معلم تأسيس ابتدائي",
    img: "/assets/imgs/wael-ahmed-hamza.jpeg",
    subjects: ["تأسيس"],
    rating: "5.0",
    students: "60+",
    bio: "خبرة 24 عاماً في تأسيس طلاب المرحلة الابتدائية في مدينة تبوك.",
    badge: "خبير 24 عاماً",
    experienceYears: 24,
    city: "تبوك",
    online: false,
    offline: true,
    stages: ["ابتدائي"],
    gender: "male",
  }),
  make({
    id: "majed-galal-eldeep",
    name: "ماجد جلال عبدالفتاح الديب",
    role: "معلم متابعة وعلم نفس",
    img: "/assets/imgs/majed-galal-eldeep.jpeg",
    subjects: ["متابعة جميع المواد", "علم نفس", "علم اجتماع"],
    rating: "5.0",
    students: "45+",
    bio: "خبرة 17 سنة. معلم متابعة للمرحلة الابتدائية والمتوسطة، ومتخصص في علم النفس والاجتماع للمرحلة الجامعية.",
    badge: "خبير 17 سنة",
    experienceYears: 17,
    city: "تبوك",
    phone: "0581636766",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "جامعة"],
    gender: "male",
  }),
  make({
    id: "mostafa-samir-mohammed",
    name: "مصطفى سمير محمد",
    role: "معلم مهارات رقمية وحاسب",
    img: "/assets/imgs/mostafa-samir-mohammed.jpeg",
    subjects: ["الحاسب الآلي", "مهارات رقمية", "فوتوشوب"],
    rating: "5.0",
    students: "25+",
    bio: "تدريس مادة المهارات الرقمية للمرحلة المتوسطة وإعطاء دورات احترافية في برنامج الفوتوشوب.",
    badge: "مدرب حاسب",
    experienceYears: 2,
    city: "تبوك",
    phone: "0539097986",
    online: true,
    offline: false,
    stages: ["متوسط"],
    gender: "male",
  }),
  make({
    id: "mohammed-elsayed-saleh",
    name: "محمد السيد صالح",
    role: "مدرس رياضيات",
    img: "/assets/imgs/mohammed-elsayed-saleh.jpeg",
    subjects: ["رياضيات"],
    rating: "5.0",
    students: "50+",
    bio: "مدرس رياضيات خبير للمرحلتين الابتدائية والمتوسطة بمدينة تبوك.",
    badge: "خبير 15 سنة",
    experienceYears: 15,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط"],
    gender: "male",
  }),
  make({
    id: "dr-mohammed-ahmed-samir",
    name: "د. محمد أحمد سمير عبد الظاهر",
    role: "خبير كيمياء",
    img: "/assets/imgs/dr-mohammed-ahmed-samir.jpeg",
    subjects: ["كيمياء"],
    rating: "5.0",
    students: "130+",
    bio: "خبرة 30 عاماً في تدريس مادة الكيمياء للمراحل الثانوية والجامعية.",
    badge: "خبير 30 سنة",
    experienceYears: 30,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "al-nasser",
    name: "أ/ ناصر",
    role: "معلم رياضيات وتأسيس",
    img: "/assets/imgs/al-nasser.jpeg",
    subjects: ["رياضيات", "تأسيس", "قراءة وكتابة"],
    rating: "5.0",
    students: "40+",
    bio: "خبرة 10 سنوات داخل المملكة في تدريس الرياضيات ومتابعة الصفوف الأولية وتأسيس القراءة والكتابة.",
    badge: "خبير 10 سنوات",
    experienceYears: 10,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط"],
    gender: "male",
  }),
  make({
    id: "ahmed-al-sarangawy",
    name: "احمد السرنجاوي",
    role: "معلم رياضيات وقرآن",
    img: "/assets/imgs/ahmed-al-sarangawy.jpeg",
    subjects: ["رياضيات", "تأسيس", "قرآن"],
    rating: "5.0",
    students: "75+",
    bio: "معلم رياضيات بمدارس العصر النموذجية. خبير تأسيس وقرآن بالأحكام لمدة 23 سنة.",
    badge: "خبير 23 سنة",
    experienceYears: 23,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط"],
    gender: "male",
  }),
  make({
    id: "mahmoud-el-naggar",
    name: "محمود النجار",
    role: "معلم خبير متميز",
    img: "/assets/imgs/mahmoud-el-naggar.jpeg",
    subjects: ["متابعة", "مواد عامة"],
    rating: "5.0",
    students: "90+",
    bio: "خبرة 27 سنة في التعليم بمدارس فرسان الشمال النموذجية بتبوك.",
    badge: "خبير 27 سنة",
    experienceYears: 27,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "fathy-soliman-shalaby",
    name: "فتحي سليمان شلبي",
    role: "معلم علوم وكيمياء",
    img: "/assets/imgs/fathy-soliman-shalaby.jpeg",
    subjects: ["علوم", "كيمياء"],
    rating: "5.0",
    students: "65+",
    bio: "خبرة 20 عاماً في تدريس العلوم والكيمياء لجميع المراحل الدراسية.",
    badge: "خبير 20 سنة",
    experienceYears: 20,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "hamada-hussein-mahmoud",
    name: "حماده حسين محمود",
    role: "معلم لغة عربية وقدرات",
    img: "/assets/imgs/hamada-hussein-mahmoud.jpeg",
    subjects: ["لغة عربية", "قدرات لفظي"],
    rating: "5.0",
    students: "80+",
    bio: "خبرة 23 عاماً في تدريس اللغة العربية لجميع المراحل والقدرات والجامعة والقدرات اللفظي.",
    badge: "خبير 23 عاماً",
    experienceYears: 23,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "hamada-ahmed-abdelmaguid",
    name: "حمادة أحمد عبدالمجيد",
    role: "مدرس خبير لغة إنجليزية",
    img: "/assets/imgs/hamada-ahmed-abdelmaguid.jpeg",
    subjects: ["لغة إنجليزية"],
    rating: "5.0",
    students: "100+",
    bio: "خبرة 26 سنة في تدريس اللغة الإنجليزية لجميع المراحل والجامعات. عمل 22 سنة في المملكة.",
    badge: "خبير 26 سنة",
    experienceYears: 26,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "aya-samir-mohammed",
    name: "اية سمير محمد",
    role: "معلمة تأسيس وعلوم",
    img: "/assets/imgs/aya-samir-mohammed.jpeg",
    subjects: ["علوم", "لغة إنجليزية", "تأسيس"],
    rating: "5.0",
    students: "20+",
    bio: "تدريس مادة العلوم باللغة الإنجليزية وتأسيس اللغة الإنجليزية للصفوف الأولى.",
    badge: "تأسيس متميزة",
    experienceYears: 5,
    city: "مصر (أونلاين)",
    phone: "01030815380",
    online: true,
    offline: false,
    stages: ["ابتدائي"],
    gender: "female",
  }),
  make({
    id: "mohammed-ibrahim-rushdi",
    name: "محمد إبراهيم رشدي",
    role: "مشرف لغة عربية ودراسات إسلامية",
    img: "/assets/imgs/mohammed-ibrahim-rushdi.jpeg",
    subjects: ["لغة عربية", "دراسات أدبية", "فقه", "توحيد"],
    rating: "5.0",
    students: "90+",
    bio: "خريج جامعة الأزهر، خبرة 20 عاماً. مشرف حالي على مدرسي اللغة العربية والاسلاميات ودرس بمدارس منارة العصر الثانوية.",
    badge: "مشرف تربوي",
    experienceYears: 20,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ثانوي"],
    gender: "male",
  }),
  make({
    id: "reda-emam-elshanawy",
    name: "رضا إمام الشناوي الدسوقي",
    role: "معلم لغة إنجليزية",
    img: "/assets/imgs/reda-emam-elshanawy.jpeg",
    subjects: ["لغة إنجليزية", "تأسيس"],
    rating: "5.0",
    students: "75+",
    bio: "خبرة 22 سنة في تأسيس وتدريس اللغة الإنجليزية للمراحل الابتدائية والمتوسطة والثانوية والجامعية.",
    badge: "خبير 22 سنة",
    experienceYears: 22,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "mahmoud-abdelhamid-dorra",
    name: "محمود عبد الحميد دره",
    role: "معلم صفوف أولية",
    img: "/assets/imgs/mahmoud-abdelhamid-dorra.jpeg",
    subjects: ["لغة عربية", "تأسيس"],
    rating: "5.0",
    students: "40+",
    bio: "معلم صفوف أولية متخصص في مادة اللغة العربية، خبرة 13 سنة في التأسيس.",
    badge: "خبير 13 سنة",
    experienceYears: 13,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي"],
    gender: "male",
  }),
  make({
    id: "ali-muslim",
    name: "أستاذ علي مسلم",
    role: "معلم قرآن وتجويد",
    img: "/assets/imgs/ali-muslim.jpeg",
    subjects: ["قرآن كريم", "تجويد"],
    rating: "5.0",
    students: "85+",
    bio: "خبير في تحفيظ القرآن الكريم وأحكام التجويد لمدة 18 عاماً.",
    badge: "خبير 18 سنة",
    experienceYears: 18,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "mohammed-safwat-omar",
    name: "محمد صفوت محمد عمر",
    role: "معلم فيزياء",
    img: "/assets/imgs/mohammed-safwat-omar.jpeg",
    subjects: ["الفيزياء"],
    rating: "5.0",
    students: "70+",
    bio: "خبرة 23 سنة في تدريس مادة الفيزياء لجميع المراحل الدراسية بتبوك.",
    badge: "خبير 23 سنة",
    experienceYears: 23,
    city: "تبوك",
    phone: "0575850414",
    online: true,
    offline: true,
    stages: ["ثانوي"],
    gender: "male",
  }),
  make({
    id: "tharwat-mostafa-hassan",
    name: "ثروت مصطفى حسن",
    role: "معلم لغة عربية",
    img: "/assets/imgs/tharwat-mostafa-hassan.jpeg",
    subjects: ["اللغة العربية", "تأسيس"],
    rating: "5.0",
    students: "90+",
    bio: "خبرة 26 سنة في تدريس اللغة العربية وتأسيس الطلاب في المرحلة الابتدائية.",
    badge: "خبير 26 سنة",
    experienceYears: 26,
    city: "تبوك",
    phone: "0596595907",
    online: true,
    offline: false,
    stages: ["ابتدائي"],
    gender: "male",
  }),
  make({
    id: "ashraf-hashem-maghrabi",
    name: "أشرف هاشم مغربي",
    role: "معلم تأسيس صفوف أولية",
    img: "/assets/imgs/ashraf-hashem-maghrabi.jpeg",
    subjects: ["اللغة العربية", "تأسيس"],
    rating: "5.0",
    students: "100+",
    bio: "تأسيس الصفوف الأولية خبرة 26 عام في تبوك داخل المملكة. خبرة إجمالية 30 عاماً.",
    badge: "خبير 30 عاماً",
    experienceYears: 30,
    city: "تبوك",
    phone: "0540736589",
    online: false,
    offline: true,
    stages: ["ابتدائي"],
    gender: "male",
  }),
  make({
    id: "islam-nasser-mohammed",
    name: "إسلام ناصر محمد",
    role: "معلم لغة عربية وتأسيس",
    img: "/assets/imgs/islam-nasser-mohammed.jpeg",
    subjects: ["لغة عربية", "تأسيس"],
    rating: "5.0",
    students: "25+",
    bio: "معلم لغة عربية متخصص في التأسيس بخبرة 5 سنوات بمدينة تبوك.",
    badge: "تأسيس متميز",
    experienceYears: 5,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي"],
    gender: "male",
  }),
  make({
    id: "ayman-rateb-mohammed",
    name: "أيمن راتب محمد عبد الظاهر",
    role: "معلم لغة عربية خبير",
    img: "/assets/imgs/ayman-rateb-mohammed.jpeg",
    subjects: ["لغة عربية"],
    rating: "5.0",
    students: "95+",
    bio: "ليسانس آداب وتربية، خبرة 27 سنة منها 24 سنة داخل المملكة العربية السعودية.",
    badge: "خبير 27 عاماً",
    experienceYears: 27,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "abdelbadie-abdelalim",
    name: "عبدالبديع عبدالعليم",
    role: "معلم قدرات لفظي وتأسيس",
    img: "/assets/imgs/abdelbadie-abdelalim.jpeg",
    subjects: ["قدرات لفظي", "تأسيس"],
    rating: "5.0",
    students: "60+",
    bio: "معلم قدرات لفظي وتأسيس للمرحلتين الابتدائية والمتوسطة بتبوك.",
    badge: "خبير قدرات",
    experienceYears: 15,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط"],
    gender: "male",
  }),
  make({
    id: "ahmed-rashad-ahmed",
    name: "احمد رشاد احمد",
    role: "معلم لغة عربية دولي",
    img: "/assets/imgs/ahmed-rashad-ahmed.jpeg",
    subjects: ["لغة عربية", "تأسيس"],
    rating: "5.0",
    students: "40+",
    bio: "خبرة 8 سنوات في المدارس الدولية بتبوك، متخصص في التأسيس والحقيبة الكاملة.",
    badge: "خبرة دولية",
    experienceYears: 8,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي"],
    gender: "male",
  }),
  make({
    id: "heba-mohammed-mahmoud",
    name: "هبه محمد محمود",
    role: "معلمة تأسيس وقرآن",
    img: "/assets/imgs/heba-mohammed-mahmoud.jpeg",
    subjects: ["تأسيس", "قرآن كريم", "قراءات"],
    rating: "5.0",
    students: "35+",
    bio: "معلمة تأسيس حاصلة على إجازة في القراءات، خبرة 10 سنوات في التعليم أونلاين.",
    badge: "مجازة بالقراءات",
    experienceYears: 10,
    city: "تبوك",
    online: true,
    offline: false,
    stages: ["ابتدائي"],
    gender: "female",
  }),
  make({
    id: "mustafa-awad",
    name: "مصطفى عوض",
    role: "معلم دراسات إسلامية + قرآن",
    img: "/assets/imgs/mostafa-awad.jpeg",
    subjects: ["دراسات إسلامية", "قرآن كريم", "تأسيس"],
    rating: "5.0",
    students: "45+",
    bio: "معلم الدراسات الإسلامية لجميع المراحل الدراسية. معلم للقرآن الكريم بجمعية تحفيظ القرآن الكريم بتبوك. تأسيس الطلاب صغارًا وكبارًا لقراءة كتاب الله تعالى بالقاعدة النورانية.",
    badge: "تأسيس وقرآن",
    experienceYears: 20,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "mustafa",
    name: "مصطفى",
    role: "معلم تاسيس صفوف اوليه و متوسطه بدرس لغتى و انجليزى و رياضيات",
    img: "/assets/imgs/mostafa-general.jpeg",
    subjects: ["تأسيس", "لغتي", "لغة إنجليزية", "رياضيات"],
    rating: "5.0",
    students: "60+",
    bio: "معلم تأسيس للصفوف الابتدائية والمتوسطة. دروس حضورية فقط، يتوفر للذهاب إلى منزل الطالب. خبرة 22 سنة.",
    badge: "خبير 22 سنة",
    experienceYears: 22,
    city: "تبوك",
    online: false,
    offline: true,
    stages: ["ابتدائي", "متوسط"],
    gender: "male",
  }),
  make({
    id: "raft-zakaria",
    name: "رأفت زكريا",
    role: "مدرس رياضيات — جميع المراحل والجامعة",
    img: "/assets/imgs/raft-zakaria.jpeg",
    subjects: ["رياضيات"],
    rating: "5.0",
    students: "30+",
    bio: "ماجستير في الرياضيات. مدرس لجميع المراحل الدراسية والجامعية.",
    badge: "ماجستير رياضيات",
    experienceYears: 5,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "nasma",
    name: "مس نسمه",
    role: "مدرسة لغة عربية + تأسيس",
    img: "/assets/imgs/nasma.jpeg",
    subjects: ["لغة عربية", "تأسيس"],
    rating: "5.0",
    students: "25+",
    bio: "دبلومة معلمات وتنمية مهارات، خبرة في تأسيس الطلاب وتعليم اللغة العربية للمناهج المصري والسعودي. منذ 4 سنوات متخصصة في التأسيس.",
    badge: "تأسيس متميزة",
    experienceYears: 7,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي"],
    gender: "female",
  }),
  make({
    id: "mustafa-kamal-badawi",
    name: "مصطفى كمال بدوي",
    role: "مدرس تأسيس صفوف أولية وعليا ومواد المتوسط + لغة عربية + صعوبات تعلم",
    img: "/assets/imgs/educational-consultant.jpeg",
    subjects: ["لغة عربية", "تأسيس", "تخاطب", "صعوبات تعلم", "تنمية مهارات"],
    rating: "5.0",
    students: "55+",
    bio: "خبرة 15 سنة في المنهج السعودي، متخصص في تأسيس الطلاب، تعديل السلوك، وصعوبات التعلم، وتنمية المهارات.",
    badge: "خبير 15 سنة",
    experienceYears: 15,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط"],
    gender: "male",
  }),
  make({
    id: "hamada-farag",
    name: "Hamada Farag",
    role: "مدرس لغة إنجليزية + STEP",
    img: "/assets/imgs/Hamada farag.jpeg",
    subjects: ["لغة إنجليزية"],
    rating: "5.0",
    students: "80+",
    bio: "معلم ومدرب معتمد للغة الإنجليزية. تأسيس من الصفر إلى الاحتراف، دورات STEP، وتحضير جامعي.",
    badge: "خبير إنجليزي",
    experienceYears: 20,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "hamouda-mohamed",
    name: "حمودة محمد حمودة",
    role: "مدرس لغة عربية + تربية إسلامية",
    img: "/assets/imgs/hamouda-mohammed-hamouda.jpeg",
    subjects: ["لغة عربية", "تربية إسلامية", "قرآن كريم"],
    rating: "5.0",
    students: "45+",
    bio: "معلم أول لغة عربية وتربية إسلامية، متخصص في تأسيس القراءة والكتابة وتحفيظ القرآن بأسلوب مبسط.",
    badge: "خبير 14 سنة",
    experienceYears: 14,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط"],
    phone: "0551791376",
    gender: "male",
  }),
  make({
    id: "mustafa-ezzeldin-ibrahim",
    name: "مصطفى عزالدين ابراهيم",
    role: "مدرس رياضيات + قدرات + تحصيلي",
    img: "/assets/imgs/mostafa-ezzeldin.jpeg",
    subjects: ["رياضيات", "قدرات", "تحصيلي"],
    rating: "5.0",
    students: "70+",
    bio: "خبير رياضيات متميز في تبوك.",
    badge: "خبير رياضيات",
    experienceYears: 25,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ثانوي"],
    gender: "male",
  }),
  make({
    id: "fawzi-abdelalim",
    name: "فوزي عبدالعليم محمد مبارك",
    role: "مدرس محاسبة وعلوم إدارية — جامعي",
    img: "/assets/imgs/fawzi-abdelalim.jpeg",
    subjects: ["محاسبة", "علوم إدارية"],
    rating: "5.0",
    students: "150+",
    bio: "خبرة 36 سنة في التدريس الجامعي في جميع فروع المحاسبة.",
    badge: "بروفيسور محاسبة",
    experienceYears: 36,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["جامعة"],
    gender: "male",
  }),
  make({
    id: "eid-abdo",
    name: "عيد عبده",
    role: "معلم تأسيس ومتابعة",
    img: "/assets/imgs/eid-abdo.jpeg",
    subjects: ["تأسيس", "لغتي", "رياضيات"],
    rating: "5.0",
    students: "60+",
    bio: "خبير في تأسيس لغتي ورياضيات المرحلة الابتدائية، ومتابعة لغتي لجميع المراحل الدراسية.",
    badge: "خبير 25 سنة",
    experienceYears: 25,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "arwa-abdelnasser-abdelhamid",
    name: "أروى عبد الناصر عبد الحميد",
    role: "مدرسة Science — International Section",
    img: "/assets/imgs/arwa-abdelnasser-abdelhamid.jpeg",
    subjects: ["Science", "كيمياء"],
    rating: "5.0",
    students: "30+",
    bio: "بكالوريوس علوم قسم كيمياء خاصة بتقدير امتياز مع مرتبة الشرف، وحاصلة على الماجستير في الكيمياء غير العضوية التطبيقية. تعمل حالياً في مدرسة دولية.",
    badge: "ماجستير كيمياء",
    experienceYears: 5,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "female",
  }),
  make({
    id: "elgharib-awad-elgharib",
    name: "الغريب عوض الغريب",
    role: "معلم رياضيات خبير",
    img: "/assets/imgs/elgharib-awad-elgharib.jpeg",
    subjects: ["رياضيات"],
    rating: "5.0",
    students: "100+",
    bio: "خبرة ٣٠ سنة في تدريس مادة الرياضيات للمرحلتين الابتدائية والمتوسطة بمدينة تبوك.",
    badge: "خبير 30 سنة",
    experienceYears: 30,
    city: "تبوك",
    phone: "0566011642",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط"],
    gender: "male",
  }),
  make({
    id: "ashour-mohammed-issa",
    name: "عاشور محمد عيسى",
    role: "معلم رياضيات",
    img: "/assets/imgs/ashour-mohammed-issa.jpeg",
    subjects: ["رياضيات"],
    rating: "5.0",
    students: "50+",
    bio: "معلم رياضيات متخصص للمراحل الابتدائية والمتوسطة والثانوية.",
    badge: "معلم رياضيات",
    experienceYears: 10,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
];
