export type Tier = "platinum" | "gold" | "silver" | "bronze";

export type Teacher = {
  id: string;
  name: string;
  role: string;
  img: string;
  subjects: string[];
  rating: string;
  students: string;
  bio: string;
  badge: string;
  experienceYears: number;
  city: string;
  phone?: string;
  online: boolean;
  offline: boolean;
  stages: string[];
  gender: "male" | "female";
  // Computed
  motqenScore: number;
  tier: Tier;
};

// ──────────────────────────────────────────────────────────
// 🎯 MOTQEN SCORE FORMULA (out of 100)
//
//  • تقييم الأهالي      → 30 pts   (rating / 5) × 30
//  • سنوات الخبرة        → 25 pts   min(years / 30, 1) × 25
//  • تنوع المواد         → 15 pts   min(subjects.len / 5, 1) × 15
//  • تنوع المراحل        → 10 pts   min(stages.len / 4, 1) × 10
//  • التوفر (أون+أوف)    → 20 pts   online×10 + offline×10
//
//  TIERS:
//    🏆 بلاتيني   ≥ 90
//    ⭐ ذهبي      80–89
//    🥈 فضي       70–79
//    🥉 برونزي    < 70
// ──────────────────────────────────────────────────────────

function calcScore(t: Omit<Teacher, "motqenScore" | "tier">): number {
  const ratingScore = (parseFloat(t.rating) / 5) * 30;
  const expScore = Math.min(t.experienceYears / 30, 1) * 25;
  const subjectScore = Math.min(t.subjects.length / 5, 1) * 15;
  const stageScore = Math.min(t.stages.length / 4, 1) * 10;
  const availScore = (t.online ? 10 : 0) + (t.offline ? 10 : 0);
  return Math.round(
    ratingScore + expScore + subjectScore + stageScore + availScore,
  );
}

function getTier(score: number): Tier {
  if (score >= 90) return "platinum";
  if (score >= 80) return "gold";
  if (score >= 70) return "silver";
  return "bronze";
}

function make(t: Omit<Teacher, "motqenScore" | "tier">): Teacher {
  const score = calcScore(t);
  return { ...t, motqenScore: score, tier: getTier(score) };
}

// ──────────────────────────────────────────────────────────
export const TIER_META: Record<
  Tier,
  {
    label: string;
    emoji: string;
    color: string;
    bg: string;
    border: string;
    glow: string;
  }
> = {
  platinum: {
    label: "بلاتيني",
    emoji: "🏆",
    color: "text-cyan-300",
    bg: "bg-cyan-400/10",
    border: "border-cyan-400/30",
    glow: "shadow-cyan-400/20",
  },
  gold: {
    label: "ذهبي",
    emoji: "⭐",
    color: "text-yellow-400",
    bg: "bg-yellow-400/10",
    border: "border-yellow-400/30",
    glow: "shadow-yellow-400/15",
  },
  silver: {
    label: "فضي",
    emoji: "🥈",
    color: "text-slate-300",
    bg: "bg-slate-400/10",
    border: "border-slate-400/25",
    glow: "shadow-slate-400/10",
  },
  bronze: {
    label: "برونزي",
    emoji: "🥉",
    color: "text-orange-400",
    bg: "bg-orange-400/8",
    border: "border-orange-400/20",
    glow: "shadow-orange-400/10",
  },
};

export const SCORE_CRITERIA = [
  {
    label: "تقييم الأهالي",
    max: 30,
    icon: "⭐",
    desc: "بناءً على تقييمات أولياء الأمور من 5 نجوم",
  },
  {
    label: "سنوات الخبرة",
    max: 25,
    icon: "💼",
    desc: "أقصى نقاط لـ 30 سنة فأكثر",
  },
  {
    label: "تنوع المواد",
    max: 15,
    icon: "📚",
    desc: "كلما زادت المواد زادت النقاط (أقصى 5 مواد)",
  },
  {
    label: "تنوع المراحل",
    max: 10,
    icon: "🎓",
    desc: "من ابتدائي حتى جامعي (أقصى 4 مراحل)",
  },
  {
    label: "التوفر",
    max: 20,
    icon: "💻",
    desc: "10 نقاط للأونلاين + 10 نقاط للأوفلاين",
  },
];

// ──────────────────────────────────────────────────────────
export const teachers: Teacher[] = [
  make({
    id: "mohammed-abu-alhadid",
    name: "محمد أبو الحديد",
    role: "مدرس لغة عربية + قدرات لفظي",
    img: "/assets/imgs/mohammed-abu-alhadid.jpeg",
    subjects: ["لغة عربية", "قدرات لفظي", "بلاغة"],
    rating: "5.0",
    students: "65+",
    bio: "خبرة 35 سنة في تدريس اللغة العربية لجميع المراحل مع تخصص في القدرات اللفظي والبلاغة.",
    badge: "خبير 35 سنة",
    experienceYears: 35,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "ahmed-antar",
    name: "أحمد عنتر (أبو محمد)",
    role: "مدرس لغة إنجليزية — تأسيس وجميع المراحل",
    img: "/assets/imgs/ahmed-antar.jpeg",
    subjects: ["لغة إنجليزية", "تأسيس"],
    rating: "5.0",
    students: "70+",
    bio: "خبرة 32 سنة في تأسيس وتعليم اللغة الإنجليزية من الصفر حتى المستويات المتقدمة والجامعية.",
    badge: "خبير 32 سنة",
    experienceYears: 32,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي", "جامعي"],
    gender: "male",
  }),
  make({
    id: "hisham-mohammed",
    name: "هشام محمد",
    role: "مدرس رياضيات — جميع المراحل + قدرات",
    img: "/assets/imgs/hisham-mohammed.jpeg",
    subjects: ["رياضيات", "قدرات كمي"],
    rating: "5.0",
    students: "60+",
    bio: "خبرة 30 سنة في تدريس الرياضيات مع تبسيط المفاهيم وإعداد الطلاب لاختبارات القدرات.",
    badge: "خبير 30 سنة",
    experienceYears: 30,
    city: "تبوك",
    online: true,
    offline: false,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "mohammed-shaarawi",
    name: "محمد الشعراوي",
    role: "معلم قرآن + عربي + إنجليزي",
    img: "/assets/imgs/mohammed-shaarawi.jpeg",
    subjects: ["قرآن كريم", "لغة عربية", "لغة إنجليزية"],
    rating: "5.0",
    students: "80+",
    bio: "خبرة أكثر من 30 سنة في المملكة في تدريس القرآن والمناهج الدراسية وتأسيس الطلاب.",
    badge: "خبير المملكة",
    experienceYears: 30,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط"],
    gender: "male",
  }),
  make({
    id: "ismaeel-abdelmoghni",
    name: "إسماعيل عبد المغني",
    role: "مدرس لغة إنجليزية — جميع المناهج",
    img: "/assets/imgs/ismaeel-abdelmoghni.jpeg",
    subjects: ["لغة إنجليزية"],
    rating: "5.0",
    students: "55+",
    bio: "خبرة 28 سنة في تدريس المناهج الحكومية والأهلية والدولية (أمريكي / بريطاني).",
    badge: "International",
    experienceYears: 28,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "ibrahim-eid",
    name: "إبراهيم عيد",
    role: "مدرس لغة إنجليزية — جميع المراحل",
    img: "/assets/imgs/ibrahim-eid.jpeg",
    subjects: ["لغة إنجليزية"],
    rating: "5.0",
    students: "50+",
    bio: "خبرة 27 سنة في تدريس اللغة الإنجليزية لجميع المراحل مع أسلوب مبسط يركز على الفهم والتطبيق العملي.",
    badge: "خبير 25+ سنة",
    experienceYears: 27,
    city: "تبوك",
    online: true,
    offline: false,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "ahmed-ata",
    name: "أحمد عطا صابر",
    role: "معلم خبير لغة إنجليزية + تأسيس شامل",
    img: "/assets/imgs/ahmed-ata-saber.jpg",
    subjects: ["إنجليزي", "رياضيات", "علوم", "تأسيس"],
    rating: "5.0",
    students: "25+ سنة خبرة",
    bio: "يتميز بقدرته على تأسيس الطلاب من الصفر وحتى الاحتراف، مع تبسيط المناهج بطريقة تناسب الجميع.",
    badge: "خبير تأسيس",
    experienceYears: 25,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "dr-badr",
    name: "الأستاذ بدر فايد",
    role: "مدرس اللغة الإنجليزية | مناهج متقدمة",
    img: "/assets/imgs/dr.badr.jpg",
    subjects: ["إنجليزي", "تأسيس لغة", "جامعي"],
    rating: "5.0",
    students: "22+ سنة خبرة",
    bio: "يمتلك خبرة طويلة في تدريس اللغة الإنجليزية وفق أحدث المناهج، ويركّز على بناء أساس قوي للطالب.",
    badge: "خبير إنجليزي",
    experienceYears: 22,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["متوسط", "ثانوي", "جامعي"],
    gender: "male",
  }),
  make({
    id: "sayed-qaoud",
    name: "سيد قاعود",
    role: "معلم تأسيس وتحفيظ قرآن",
    img: "/assets/imgs/sayed-qaoud.jpeg",
    subjects: ["تأسيس", "قرآن كريم"],
    rating: "5.0",
    students: "40+",
    bio: "خبرة 20 سنة في تأسيس الطلاب وتحفيظ القرآن بأسلوب تربوي مبسط ومؤثر.",
    badge: "محفظ قرآن",
    experienceYears: 20,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي"],
    gender: "male",
  }),
  make({
    id: "mohammed-ali",
    name: "محمد علي محجوب",
    role: "معلم خبير لغة إنجليزية",
    img: "/assets/imgs/mohammed-ali-mahjoub.jpeg",
    subjects: ["إنجليزي", "مناهج دولية", "جامعي"],
    rating: "5.0",
    students: "20+ سنة خبرة",
    bio: "يتميز بخبرة طويلة في تعليم اللغة إنجليزية لمختلف الأعمار، ويعتمد على أساليب تفاعلية حديثة.",
    badge: "خبير إنجليزي",
    experienceYears: 20,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["متوسط", "ثانوي", "جامعي"],
    gender: "male",
  }),
  make({
    id: "nader-saber",
    name: "نادر صابر",
    role: "مدرس ابتدائي شامل",
    img: "/assets/imgs/nader-saber.jpeg",
    subjects: ["لغتي", "لغة إنجليزية", "رياضيات"],
    rating: "5.0",
    students: "45+",
    bio: "خبرة أكثر من 20 سنة في تأسيس طلاب المرحلة الابتدائية في جميع المواد الأساسية.",
    badge: "خبير ابتدائي",
    experienceYears: 20,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي"],
    gender: "male",
  }),
  make({
    id: "abdelnaser",
    name: "عبدالناصر محمد إبراهيم",
    role: "خبير منهج سعودي — 14 عاماً",
    img: "/assets/imgs/abdelnaser.jpg",
    subjects: ["قدرات", "تحصيلي", "ثانوي"],
    rating: "4.9",
    students: "14 سنة خبرة",
    bio: "يساعد الطلاب على تحقيق نتائج متميزة في القدرات والتحصيلي باستراتيجيات ذكية مجربة على مدى 14 عاماً.",
    badge: "خبير قدرات",
    experienceYears: 14,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ثانوي", "جامعي"],
    gender: "male",
  }),
  make({
    id: "yaser-saber",
    name: "ياسر صابر",
    role: "معلم متميز",
    img: "/assets/imgs/yaser-saber.jpeg",
    subjects: ["تأسيس", "متابعة", "رياضيات"],
    rating: "4.8",
    students: "خبرة واسعة",
    bio: "مدرس خبير يركز على تحسين مستوى الطلاب وتطوير مهاراتهم الدراسية بشكل ملحوظ.",
    badge: "معلم متميز",
    experienceYears: 12,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط"],
    gender: "male",
  }),
  make({
    id: "ahmed-hashem",
    name: "أحمد هاشم سباق",
    role: "مدرس أساسي — ابتدائي",
    img: "/assets/imgs/ahmed-hashem.jpg",
    subjects: ["لغتي", "رياضيات", "تأسيس"],
    rating: "5.0",
    students: "20+",
    bio: "يركّز على تعليم الأطفال بطريقة تفاعلية تضمن الفهم العميق، مما يبني أساساً قويًا في القراءة والكتابة والحساب.",
    badge: "مدرس تأسيس",
    experienceYears: 10,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي"],
    gender: "male",
  }),
  make({
    id: "ramadan-al-hawari",
    name: "رمضان الهواري",
    role: "مدرس لغة إنجليزية + ترجمة",
    img: "/assets/imgs/ramadan-al-hawari.jpeg",
    subjects: ["لغة إنجليزية"],
    rating: "5.0",
    students: "30+",
    bio: "خبرة في التعليم الأكاديمي والترجمة مع أسلوب تفاعلي يضمن أعلى استفادة للطالب.",
    badge: "تفاعلي",
    experienceYears: 10,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "abdelmonem-hossam",
    name: "عبدالمنعم حسام",
    role: "مدرس إنجليزي + رياضيات",
    img: "/assets/imgs/abdelmonem-hossam.jpeg",
    subjects: ["لغة إنجليزية", "رياضيات"],
    rating: "5.0",
    students: "25+",
    bio: "خبرة 9 سنوات في تبسيط المواد العلمية واللغوية وتحسين مستوى الطلاب.",
    badge: "متعدد المهارات",
    experienceYears: 9,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط"],
    gender: "male",
  }),
  make({
    id: "mohammed-abdelhakim",
    name: "محمد عبد الحكيم",
    role: "مدرس أحياء + تأسيس",
    img: "/assets/imgs/mohammed-abdelhakim.jpeg",
    subjects: ["أحياء", "تأسيس"],
    rating: "5.0",
    students: "25+",
    bio: "خبرة 6 سنوات في المملكة، يركز على تبسيط الأحياء وبناء أساس قوي للطلاب.",
    badge: "مدرس نشط",
    experienceYears: 6,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "osama-ali",
    name: "أسامة علي عبدالجواد",
    role: "علوم وأحياء وقرآن كريم",
    img: "/assets/imgs/osama ali.jpg",
    subjects: ["علوم", "أحياء", "قرآن", "تجويد"],
    rating: "4.8",
    students: "5+ سنوات",
    bio: "يجمع بين العلوم الأكاديمية والتربوية، مع خبرة في تحفيظ القرآن والتجويد بأسلوب شيّق.",
    badge: "محفظ قرآن",
    experienceYears: 5,
    city: "تبوك",
    online: true,
    offline: false,
    stages: ["ابتدائي", "متوسط"],
    gender: "male",
  }),
  make({
    id: "mohammed-ahmed-saad",
    name: "محمد أحمد سعد",
    role: "متخصص قدرات + تحصيلي + علوم",
    img: "/assets/imgs/mohammed-ahmed-saad.jpg",
    subjects: ["قدرات", "تحصيلي", "علوم"],
    rating: "4.9",
    students: "5 سنوات خبرة",
    bio: "يساعد الطلاب على تحسين نتائجهم من خلال التدريب المكثف على نماذج الاختبارات الحديثة.",
    badge: "خبير قدرات",
    experienceYears: 5,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ثانوي", "جامعي"],
    gender: "male",
  }),
  make({
    id: "hashem-sewak",
    name: "هاشم السواق",
    role: "متخصص في مادة الكيمياء",
    img: "/assets/imgs/hashem-al-sawaq.jpg",
    subjects: ["كيمياء", "علوم"],
    rating: "4.8",
    students: "3 سنوات خبرة",
    bio: "يقدّم شرحًا مبسطًا لمادة الكيمياء يساعد الطلاب على فهم الأساسيات بسهولة وتحقيق نتائج أفضل.",
    badge: "مدرس كيمياء",
    experienceYears: 3,
    city: "تبوك",
    online: false,
    offline: true,
    stages: ["ثانوي"],
    gender: "male",
  }),
  make({
    id: "mahmoud-muslim",
    name: "محمود مسلم",
    role: "معلم أحياء للمرحلة الثانوية",
    img: "/assets/imgs/mahmoud-muslim.jpeg",
    subjects: ["أحياء", "تحصيلي", "علوم"],
    rating: "4.9",
    students: "3 سنوات خبرة",
    bio: "حاصل على الرخصة المهنية التعليمية تخصص الأحياء، يتميز بمستوى ممتاز في المادة العلمية.",
    badge: "خبير أحياء",
    experienceYears: 3,
    city: "تبوك",
    online: true,
    offline: false,
    stages: ["ثانوي"],
    gender: "male",
  }),
  make({
    id: "fatouh-qutb",
    name: "فتوح قطب البسيوني",
    role: "معلم خبير",
    img: "/assets/imgs/fatouh-qutb.jpg",
    subjects: ["لغة عربية", "تأسيس"],
    rating: "5.0",
    students: "خبرة طويلة",
    bio: "معلم قدير يمتلك سنوات طويلة من الخبرة في التعليم وبناء مهارات الطلاب الأساسية.",
    badge: "خبير تعليمي",
    experienceYears: 3,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "mustafa-abdelrazek",
    name: "مصطفي عبد الرازق محمد فرج",
    role: "مدرس كيمياء وعلوم — جامعي وثانوي",
    img: "/assets/imgs/mustafa-abdelrazek.jpeg",
    subjects: ["كيمياء", "علوم", "chemistry", "science", "كيمياء جامعية"],
    rating: "5.0",
    students: "15+ سنة خبرة",
    bio: "خبير في تدريس المناهج المصرية والسعودية لمناهج العلوم والكيمياء لجميع المراحل، بالإضافة إلى تدريس الكيمياء لطلاب الجامعات والكليات العلمية (طب، صيدلة، علوم). خبرة في تدريس طلاب جامعة الملك فيصل بالأحساء.",
    badge: "خبير جامعي",
    experienceYears: 15,
    city: "الأحساء",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي", "جامعي"],
    gender: "male",
  }),
  make({
    id: "ahmed-marouf",
    name: "أحمد معروف",
    role: "مدرس لغة عربية + قرآن + قدرات لفظي",
    img: "/assets/imgs/ahmed-marouf.jpeg",
    subjects: ["لغة عربية", "قرآن كريم", "قدرات لفظي"],
    rating: "5.0",
    students: "",
    bio: "",
    badge: "لغة عربية",
    experienceYears: 0,
    city: "تبوك",
    online: true,
    offline: true,
    stages: [],
    gender: "male",
  }),
  make({
    id: "hany-elawady",
    name: "هاني عبد الوهاب العوضي",
    role: "مدرس جامعة + كيمياء + فيزياء + تحصيلي",
    img: "/assets/imgs/hany-elawady.jpeg",
    subjects: ["كيمياء", "فيزياء", "تحصيلي"],
    rating: "5.0",
    students: "",
    bio: "",
    badge: "خبير جامعي",
    experienceYears: 33,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "reda-amar",
    name: "رضا محمد الصابر عمار",
    role: "مدرس كيمياء — جميع المراحل",
    img: "/assets/imgs/reda-amar.jpeg",
    subjects: ["كيمياء"],
    rating: "5.0",
    students: "",
    bio: "حاصل على بكالوريوس في العلوم والتربية تخصص فيزياء وكيمياء، يتبع أسلوبًا مبسطًا في الشرح ويتعامل مع جميع المستويات مع متابعة مستمرة لولي الأمر.",
    badge: "كيمياء",
    experienceYears: 18,
    city: "تبوك",
    online: true,
    offline: true,
    stages: [],
    gender: "male",
  }),
  make({
    id: "mohammed-abdelalim",
    name: "محمد عبدالعليم",
    role: "مدرس رياضيات + قدرات + تحصيلي",
    img: "/assets/imgs/mohammed-abdelalim.jpeg",
    subjects: ["رياضيات", "قدرات", "تحصيلي"],
    rating: "5.0",
    students: "",
    bio: "",
    badge: "رياضيات",
    experienceYears: 17,
    city: "تبوك",
    online: true,
    offline: true,
    stages: [],
    gender: "male",
  }),
  make({
    id: "ahmed-el-sayed",
    name: "أحمد السيد محمد",
    role: "مدرس تأسيس + قرآن — ابتدائي",
    img: "/assets/imgs/ahmed-elsayed.jpeg",
    subjects: ["تأسيس", "قرآن كريم"],
    rating: "5.0",
    students: "",
    bio: "مدرس تأسيس بطريقة نور البيان بشكل تدريجي وسهل، ومحفظ قرآن معتمد بجمعية تحفيظ القرآن الكريم بتبوك.",
    badge: "تأسيس وقرآن",
    experienceYears: 10,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي"],
    gender: "male",
  }),
  make({
    id: "abdelaziz-ali",
    name: "عبدالعزيز علي",
    role: "مدرس دوائر كهربائية وآلات — كليات التقنية",
    img: "/assets/imgs/abdelaziz-ali.jpeg",
    subjects: ["دوائر كهربائية 1", "دوائر كهربائية 2", "آلات تيار مستمر"],
    rating: "5.0",
    students: "",
    bio: "",
    badge: "هندسة كهربائية",
    experienceYears: 10,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["جامعة"],
    gender: "male",
  }),
  make({
    id: "mohammed-abdessalam",
    name: "محمد عبدالسلام",
    role: "مدرس لغة إنجليزية + ترجمة",
    img: "/assets/imgs/mohammed-abdessalam.jpeg",
    subjects: ["لغة إنجليزية"],
    rating: "5.0",
    students: "",
    bio: "خريج لغات وترجمة، خبرة في التدريس والتأسيس لجميع المراحل والجامعات، وخبرة في الترجمة التحريرية والفورية.",
    badge: "إنجليزي وترجمة",
    experienceYears: 8,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "mohammed-abdelhamid",
    name: "محمد عبد الحميد",
    role: "مدرس لغة إنجليزية — جميع المراحل",
    img: "/assets/imgs/mohammed-abdelhamid.jpeg",
    subjects: ["لغة إنجليزية"],
    rating: "5.0",
    students: "",
    bio: "",
    badge: "إنجليزي",
    experienceYears: 30,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "ryad-salam",
    name: "رياض عبدالعظيم سلام",
    role: "مدرس فيزياء + كيمياء + تحصيلي",
    img: "/assets/imgs/ryad-salam.jpeg",
    subjects: ["فيزياء", "كيمياء", "تحصيلي"],
    rating: "5.0",
    students: "",
    bio: "",
    badge: "فيزياء وكيمياء",
    experienceYears: 0,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "abdellatif-shaker",
    name: "عبداللطيف شاكر عبداللطيف",
    role: "مدرس شريعة إسلامية + قانون — جامعة",
    img: "/assets/imgs/abdellatif-shaker.jpeg",
    subjects: ["شريعة", "قانون"],
    rating: "5.0",
    students: "",
    bio: "",
    badge: "شريعة وقانون",
    experienceYears: 25,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["جامعة"],
    gender: "male",
  }),
  make({
    id: "mohammed-moussa",
    name: "محمد عبد الله موسى سليمان",
    role: "مدرس فيزياء — جميع المراحل",
    img: "/assets/imgs/mohammed-moussa.jpeg",
    subjects: ["فيزياء"],
    rating: "5.0",
    students: "",
    bio: "",
    badge: "فيزياء",
    experienceYears: 35,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["متوسط", "ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "ahmed-gad",
    name: "أحمد جاد",
    role: "مدرس خبير — جميع المراحل",
    img: "/assets/imgs/ahmed-gad.jpeg",
    subjects: ["لغة عربية", "تأسيس", "متابعة"],
    rating: "5.0",
    students: "جديد",
    bio: "خبرة واسعة في التدريس والتعامل مع مختلف المستويات الدراسية بأساليب حديثة ومبتكرة.",
    badge: "انضم حديثاً",
    experienceYears: 15,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "khaled-mostafa-ramadan",
    name: "خالد مصطفى رمضان محمد",
    role: "مدرس إدارة الرياضات المائية",
    img: "/assets/imgs/khaled-mostafa-ramadan.jpeg",
    subjects: ["إدارة رياضية", "رياضات مائية"],
    rating: "5.0",
    students: "",
    bio: "",
    badge: "",
    experienceYears: 12,
    city: "",
    online: true,
    offline: true,
    stages: ["جامعة"],
    gender: "male",
  }),
  make({
    id: "mohamed-noman",
    name: "محمد نعمان",
    role: "مدرس لغة إنجليزية — جميع المراحل",
    img: "/assets/imgs/mohamed-noman.jpeg",
    subjects: ["لغة إنجليزية"],
    rating: "5.0",
    students: "",
    bio: "تأسيس اللغة الإنجليزية لجميع المراحل من KG حتى الجامعة، مع خبرة في المناهج الحكومية والإنترناشونال.",
    badge: "",
    experienceYears: 12,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["KG", "ابتدائي", "متوسط", "ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "mohamed-ahmed-safwat",
    name: "محمد أحمد صفوت محمد عمر",
    role: "مدرس كيمياء — ثانوي",
    img: "/assets/imgs/mohamed-ahmed-safwat.jpeg",
    subjects: ["كيمياء"],
    rating: "5.0",
    students: "",
    bio: "",
    badge: "",
    experienceYears: 23,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ثانوي"],
    gender: "male",
  }),
  make({
    id: "tarek-abdelwahab-abdelaziz",
    name: "طارق عبدالوهاب عبدالعزيز",
    role: "مدرس لغة إنجليزية + ترجمة",
    img: "/assets/imgs/tarek-abdelwahab-abdelaziz.jpeg",
    subjects: ["لغة إنجليزية"],
    rating: "5.0",
    students: "",
    bio: "مدرس لغة إنجليزية وآدابها ومترجم حر، متخصص في اختبار STEP، خبرة طويلة في التدريس والترجمة لأكثر من 35 عامًا.",
    badge: "",
    experienceYears: 38,
    city: "تبوك",
    online: false,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    gender: "male",
  }),
  make({
    id: "ahmed-abdelkarim-al-zubaidi",
    name: "أحمد عبدالكريم الزبيدي",
    role: "مدرس أحياء + كيمياء + تحصيلي",
    img: "/assets/imgs/ahmed-abdelkarim-al-zubaidi.jpeg",
    subjects: ["أحياء", "كيمياء", "تحصيلي"],
    rating: "5.0",
    students: "",
    bio: "تدريس الأحياء والكيمياء للمرحلة الثانوية بالإضافة إلى التحصيلي، مع تدريس مواد الجامعة (Biology & Chemistry).",
    badge: "",
    experienceYears: 9,
    city: "",
    online: true,
    offline: true,
    stages: ["ثانوي", "جامعة"],
    gender: "male",
  }),
  // --- Added teachers from user request
  make({
    id: "mustafa-awad",
    name: "مصطفى عوض",
    role: "معلم دراسات إسلامية + قرآن",
    img: "/assets/imgs/مصطفى عوض.jpeg",
    subjects: ["دراسات إسلامية", "قرآن كريم", "تأسيس"],
    rating: "5.0",
    students: "",
    bio: "معلم الدراسات الإسلامية لجميع المراحل الدراسية. معلم للقرآن الكريم بجمعية تحفيظ القرآن الكريم بتبوك. تأسيس الطلاب صغارًا وكبارًا لقراءة كتاب الله تعالى بالقاعدة النورانية.",
    badge: "",
    experienceYears: 20,
    city: "تبوك",
    online: false,
    offline: false,
    stages: ["ابتدائي", "متوسط", "ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "mustafa",
    name: "مصطفى",
    role: "معلم تاسيس صفوف اوليه و متوسطه بدرس لغتى و انجليزى و رياضيات",
    img: "/assets/imgs/مصطفى.jpeg",
    subjects: ["تأسيس", "لغتي", "لغة إنجليزية", "رياضيات"],
    rating: "5.0",
    students: "",
    bio: "معلم تأسيس للصفوف الابتدائية والمتوسطة. دروس حضورية فقط، يتوفر للذهاب إلى منزل الطالب. خبرة 22 سنة.",
    badge: "",
    experienceYears: 22,
    city: "تبوك",
    online: false,
    offline: true,
    stages: ["ابتدائي", "متوسط"],
    gender: "male",
  }),
  make({
    id: "raft-zakaria",
    name: "رأفت زكريا",
    role: "مدرس رياضيات — جميع المراحل والجامعة",
    img: "/assets/imgs/رأفت زكريا.jpeg",
    subjects: ["رياضيات"],
    rating: "5.0",
    students: "",
    bio: "ماجستير في الرياضيات. مدرس لجميع المراحل الدراسية والجامعية.",
    badge: "",
    experienceYears: 5,
    city: "",
    online: false,
    offline: false,
    stages: ["ابتدائي", "متوسط", "ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "nasma",
    name: "مس نسمه",
    role: "مدرسة لغة عربية + تأسيس",
    img: "/assets/imgs/نسمه.jpeg",
    subjects: ["لغة عربية", "تأسيس"],
    rating: "5.0",
    students: "",
    bio: "دبلومة معلمات وتنمية مهارات، خبرة في تأسيس الطلاب وتعليم اللغة العربية للمناهج المصري والسعودي. منذ 4 سنوات متخصصة في التأسيس.",
    badge: "",
    experienceYears: 7,
    city: "",
    online: true,
    offline: true,
    stages: ["ابتدائي"],
    gender: "female",
  }),
  make({
    id: "arabic-teacher-unknown",
    name: "",
    role: "مدرس لغة عربية — ابتدائي ومتوسط",
    img: "",
    subjects: ["لغة عربية"],
    rating: "5.0",
    students: "",
    bio: "خبرة 7 سنوات في تدريس اللغة العربية للمراحل الابتدائية والمتوسطة.",
    badge: "",
    experienceYears: 7,
    city: "",
    online: false,
    offline: false,
    stages: ["ابتدائي", "متوسط"],
    gender: "male",
  }),
  make({
    id: "osama-mohammed-mokhtar",
    name: "أسامة محمد مختار",
    role: "مدرس لغة عربية — جميع المراحل",
    img: "/assets/imgs/أسامة محمد مختار.jpeg",
    subjects: ["لغة عربية"],
    rating: "5.0",
    students: "",
    bio: "",
    badge: "",
    experienceYears: 25,
    city: "تبوك",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    phone: "0536814973",
    gender: "male",
  }),
  make({
    id: "ahmed-badr",
    name: "أحمد بدر",
    role: "مدرس رياضيات وإحصاء — جامعي",
    img: "/assets/imgs/احمد بدر.jpeg",
    subjects: ["رياضيات", "إحصاء"],
    rating: "5.0",
    students: "",
    bio: "تدريس طلاب السنة التحضيرية وكليات العلوم والهندسة وعلوم الحاسب بجامعة تبوك وجامعة الأمير فهد بن سلطان وطلاب نيوم. متخصص في تدريس الرياضيات والإحصاء لطلبة التخصصات العلمية.",
    badge: "",
    experienceYears: 17,
    city: "تبوك",
    online: false,
    offline: false,
    stages: ["جامعة"],
    gender: "male",
  }),
  make({
    id: "basant-diab",
    name: "باسنت دياب",
    role: "دكتورة صحة نفسية وتعديل سلوك",
    img: "/assets/imgs/باسنت دياب.jpeg",
    subjects: ["صحة نفسية", "تعديل سلوك", "إرشاد أسري", "تربية خاصة"],
    rating: "5.0",
    students: "",
    bio: "دكتورة متخصصة في الصحة النفسية وتعديل السلوك، تعمل مع الأطفال والمراهقين، وعضو اتحاد المعالجين النفسيين العرب. معتمدة في الكوتشينج من ICF، ولديها خبرة في التدريب والإرشاد الأسري وتقديم البرامج الإعلامية. (السيرة مرفقة بالصورة)",
    badge: "",
    experienceYears: 0,
    city: "",
    online: false,
    offline: false,
    stages: ["أطفال", "مراهقين"],
    gender: "female",
  }),
  make({
    id: "mustafa-kamal-badawi",
    name: "مصطفى كمال بدوي",
    role: "مدرس تأسيس صفوف أولية وعليا ومواد المتوسط + لغة عربية + صعوبات تعلم",
    img: "",
    subjects: ["لغة عربية", "تأسيس", "تخاطب", "صعوبات تعلم", "تنمية مهارات"],
    rating: "5.0",
    students: "",
    bio: "خبرة 15 سنة في المنهج السعودي، متخصص في تأسيس الطلاب، تعديل السلوك، وصعوبات التعلم، وتنمية المهارات. لديه خبرة في إعداد أبحاث جامعية ودراسات عليا (ماجستير ودكتوراه) في التربية واللغة والصحة النفسية وطرق التدريس.",
    badge: "",
    experienceYears: 15,
    city: "",
    online: false,
    offline: false,
    stages: ["ابتدائي", "متوسط"],
    gender: "male",
  }),
  make({
    id: "hamada-farag",
    name: "Hamada Farag",
    role: "مدرس لغة إنجليزية + STEP",
    img: "/assets/imgs/Hamada farag.jpeg",
    subjects: ["لغة إنجليزية"],
    rating: "5.0",
    students: "",
    bio: "معلم ومدرب معتمد للغة الإنجليزية. تأسيس من الصفر إلى الاحتراف، دورات STEP، وتحضير جامعي. دروس حضورية أو أونلاين.",
    badge: "",
    experienceYears: 20,
    city: "",
    online: true,
    offline: true,
    stages: ["ثانوي", "جامعة"],
    gender: "male",
  }),
  make({
    id: "hamouda-mohamed",
    name: "حمودة محمد حمودة",
    role: "مدرس لغة عربية + تربية إسلامية",
    img: "/assets/imgs/حمودة محمد حمودة.jpeg",
    subjects: ["لغة عربية", "تربية إسلامية", "قرآن كريم"],
    rating: "5.0",
    students: "",
    bio: "معلم أول لغة عربية وتربية إسلامية، متخصص في تأسيس القراءة والكتابة وتحفيظ القرآن بأسلوب مبسط مع متابعة مستمرة. خبرة 14 سنة.",
    badge: "",
    experienceYears: 14,
    city: "تبوك - الفيصلية",
    online: true,
    offline: true,
    stages: ["ابتدائي", "متوسط"],
    phone: "0551791376",
    gender: "male",
  }),
  make({
    id: "mustafa-azaldin-ibrahim",
    name: "مصطفى عزالدين ابراهيم",
    role: "مدرس رياضيات + قدرات + تحصيلي",
    img: "/assets/imgs/مصطفى عزالدين.jpeg",
    subjects: ["رياضيات", "قدرات", "تحصيلي"],
    rating: "5.0",
    students: "",
    bio: "",
    badge: "",
    experienceYears: 25,
    city: "",
    online: false,
    offline: false,
    stages: ["ثانوي"],
    gender: "male",
  }),
  make({
    id: "fawzi-abdelalim",
    name: "فوزي عبدالعليم محمد مبارك",
    role: "مدرس محاسبة وعلوم إدارية — جامعي",
    img: "/assets/imgs/فوزي عبدالعليم.jpeg",
    subjects: ["محاسبة", "علوم إدارية"],
    rating: "5.0",
    students: "",
    bio: "خبرة 36 سنة في التدريس الجامعي في جميع فروع المحاسبة.",
    badge: "",
    experienceYears: 36,
    city: "",
    online: false,
    offline: false,
    stages: ["جامعة"],
    gender: "male",
  }),
];
